apiVersion: apps/v1
kind: Deployment
metadata:
  name: artst-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        name: artst-app
    spec:
      imagePullSecrets:
        - name: github-token # Change this with your registry hosting, ex : github-token, gitlab-token, dockerhub-token
      containers:
        - name: artst-app
          image: ghcr.io/artstio/artst:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 1
            initialDelaySeconds: 45
          env:
            - name: STARTUP_DELAY_SECONDS
              value: "40"
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: artst-service
spec:
  selector:
    name: artst-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  # externalTrafficPolicy: Cluster
  # type: LoadBalancer
