version: "3.1"

services:
  artst:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - /myapp/node_modules
    env_file:
      - .env
